before:
  hooks:
    - go mod download

builds:
  - id: git-list
    main: ./cmd/list/main.go
    binary: git-list
    ldflags:
      - -s -w 
      - -X git-get/pkg/cfg.version={{.Version}} 
      - -X git-get/pkg/cfg.commit={{.Commit}} 
      - -X git-get/pkg/cfg.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows

archives:
  - id: archive
    builds:
      - git-list
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  github:
    owner: grdl
    name: git-get


brews:
  - name: git-get
    github:
      owner: grdl
      name: homebrew-tap
    commit_author:
      name: Grzegorz Dlugoszewski
      email: git-get@grdl.dev
    folder: Formula
    homepage: "https://github.com/grdl/git-get/"
    description: "Better way to clone, organize and manage git repositories"
    test: |
      system "git-get --version"
    install: |
      bin.install "git-get"